### PR TITLE
adding favorites timeline functionality

### PR DESCRIPTION
**Pull request by clarkenciel**
attempt to address: https://github.com/jdenen/mastodon.el/issues/91

### CODE REVIEW

**Comment by clarkenciel** [comment]
hm okay this was a bit premature: i need to work on the "load-more functionality" for this since the defaults in the timeline module won't work out-of-the-box for this. @jdenen i'd rather not duplicate most of that module. how do you feel about adding adding a "fetch-more" callback to some of the timeline functions? I'd rather not have to duplicate pretty much the entire timeline module just because the endpoint for favorites is slightly different.

**Comment by alexjgriffith** [comment]
@clarkenciel I had the same issues with notifications, user profiles, and now async streams. @jdenen mentioned his plan going forward in #84. We need to get those macros done in mastodon-tl.el before we get full functionality.

**Comment by jdenen** [comment]
Yeah #84 is the approach we're going to take to extract all the commonality. Let's let this PR stand for a bit and refactor it once the #84 approach is implemented in develop. 

In the meantime, can you edit this PR to change all the isntances of "favorite" to "favourite"? 

While I'm American and do appreciate the _right_ way to spell it (😝), I want this to be as close to the vanilla Mastodon experience as possible. Eventually, we could add customization around a lot of these strings but that's gold plating that I'd rather put off for awhile.

**Comment by clarkenciel** [comment]
@jdenen @alexjgriffith sounds like a plan y'all!

**Pull request closed without merging**
